/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MonkeysImport } from './routes/monkeys'
import { Route as LocationsImport } from './routes/locations'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const MonkeysRoute = MonkeysImport.update({
  id: '/monkeys',
  path: '/monkeys',
  getParentRoute: () => rootRoute,
} as any)

const LocationsRoute = LocationsImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsImport
      parentRoute: typeof rootRoute
    }
    '/monkeys': {
      id: '/monkeys'
      path: '/monkeys'
      fullPath: '/monkeys'
      preLoaderRoute: typeof MonkeysImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/locations': typeof LocationsRoute
  '/monkeys': typeof MonkeysRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/locations': typeof LocationsRoute
  '/monkeys': typeof MonkeysRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/locations': typeof LocationsRoute
  '/monkeys': typeof MonkeysRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/locations' | '/monkeys'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/locations' | '/monkeys'
  id: '__root__' | '/' | '/about' | '/locations' | '/monkeys'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LocationsRoute: typeof LocationsRoute
  MonkeysRoute: typeof MonkeysRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LocationsRoute: LocationsRoute,
  MonkeysRoute: MonkeysRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/locations",
        "/monkeys"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/locations": {
      "filePath": "locations.tsx"
    },
    "/monkeys": {
      "filePath": "monkeys.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
